import config as cfg
import streamlit as st
import utils
from pandas import DataFrame


def match_selector(selector_key: str) -> str:
    """
    Dynamically creates inputs to generate a match key. 
    
    Generates a comp level dropdown, a match number input, and, if the comp level isn't quals, a set number input. 
    
    Returns the match key generated by the inputs.

    Args:
        selector_key (str): The key of the match selector. Serves as the start of session storage keys where the selected match is stored. Should be unique to each input.

    Returns:
        str: The match key generated by the inputs. Format will follow ``<event code>_<comp level><set number>m<match number>`` eg ``2024aztem_qm1`` or ``2024aztem_f1m1``. For quals there is no set number. 
    """
    # The "current" event code. This is the event code the user is currently looking at. This is the event code used for match selection
    current_event_code: str = st.session_state["currentEventCode"]
    # The match data for the current event code
    match_data: list = utils.get_event_schedule(st.session_state["currentEventCode"])

    # Key where the selected match is stored long-term
    session_state_key: str = f"{selector_key}_selected_match"
    # Temporary key the input saves values to
    input_key: str = f"_{selector_key}_selected_match_input"

    # If there's a match selection stored, set it as the selection. Otherwise, just use the first qual from the event.
    if session_state_key in st.session_state and st.session_state[session_state_key] != "":
        selected_match_key: str = st.session_state[session_state_key]
    elif session_state_key not in st.session_state:
        selected_match_key: str = "qm1"
        st.session_state[session_state_key] = selected_match_key

    # Convert the match key string to a dictionary
    selected_match_dict: dict = utils.match_key_to_dict(selected_match_key)

    # Initialize the session storage keys for each aspect of the match key if they don't exist
    if f"{session_state_key}_cl" not in st.session_state:
        st.session_state[f"{session_state_key}_cl"] = "qm"
    if f"{session_state_key}_mn" not in st.session_state:
        st.session_state[f"{session_state_key}_mn"] = 1
    if f"{session_state_key}_set" not in st.session_state:
        st.session_state[f"{session_state_key}_set"] = 1

    # Dynamically generate columns based on the comp level
    cols = st.columns(
        3 if st.session_state[f"{session_state_key}_cl"] != "qm"
        else 2
        )

    ##### COMP LEVEL INPUT #####
    cols[0].selectbox(
        label="Competition Level",                                                  # The label shown above the input
        options=utils.comp_level_keys,                                                    # The options the user can select
        index=utils.comp_level_keys.index(selected_match_dict["comp_level"]),             # Set the default comp level to be selected for the dropdown
        format_func=lambda x: cfg.COMP_LEVEL_KEY_TO_TEXT[x],                         # Convert the abbreviated comp level key strings to human readable names
        key=f"{input_key}_cl",                                                      # A session_state key where the data will be temporary stored. Note storage from this method is NOT the same as normal session state. It is TEMPORARY
        on_change=utils.input_change,                                                     # When the value of the input changes, run input_change with those args
        args=[f"{session_state_key}_cl", f"{input_key}_cl", True],                  # args to run input_change with on change.
    )

    ##### MATCH NUMBER INPUT #####
    cols[1].number_input(
        label="Enter Match Number",                                                 # The label shown above the input
        value=selected_match_dict["match_number"],                                  # The currently selected match number
        min_value=1,                                                                # The minimum value the input can be
        max_value=len(match_data),                                                  # The maximum value the input can be. Set to the number of matches found in the event data
        key=f"{input_key}_mn",                                                      # A session_state key where the data will be temporary stored. Note storage from this method is NOT the same as normal session state. It is TEMPORARY
        on_change=utils.input_change,                                                     # When the value of the input changes, run input_change with those args
        args=[f"{session_state_key}_mn", f"{input_key}_mn", True],                  # args to run input_change with on change.
    )

    ##### SET NUMBER INPUT #####
    # If the comp level is not quals, don't write the set number input
    if st.session_state[f"{session_state_key}_cl"] != "qm":
        # Write a number input
        cols[2].number_input(
            label="Enter Set",                                                      # The label shown above the input
            value=selected_match_dict["set_number"],                                       # The currently selected set number
            min_value=1,                                                            # The minimum value the input can be
            key=f"{input_key}_set",                                                 # A session_state key where the data will be temporary stored. Note storage from this method is NOT the same as normal session state. It is TEMPORARY
            on_change=utils.input_change,                                                 # When the value of the input changes, run input_change with those args
            args=[f"{session_state_key}_set", f"{input_key}_set", True],            # args to run input_change with on change.
        )

    # Returns the match select as stored in the session state under session_state_key
    return st.session_state[session_state_key]


def write_match_summary(match_df: DataFrame, prescouting_df: DataFrame, match_key: str) -> None:
    """Writes the alliance summaries for a match (``match_key``)

    Args:
        match_df (DataFrame): Match data DataFrame to get data from.
        match_df (DataFrame): Prescouting data DataFrame to get data from.
        match_key (str): Match key string following the format of `<event code>_<comp level><set>m<match number>`. Should be from a ``utils.match_selector``
    
    Returns:
        None. Writes the summary directly.
    """
    # Gets the current event code and match list for the current event code
    current_event_code: str = st.session_state["currentEventCode"]
    full_match_list: list = utils.get_event_schedule(current_event_code)

    # Gets the dictionary for the selected match and extracts the red teams and blue teams as lists.
    match: dict = [match
                   for match in full_match_list
                   if match["key"] == f"{st.session_state['currentEventCode']}_{match_key}"
                   ][0]
    red_teams: list = [int(team.strip("frc"))
                 for team in match["alliances"]["red"]["team_keys"]]
    blue_teams: list = [int(team.strip("frc"))
                  for team in match["alliances"]["blue"]["team_keys"]]

    # Writes two columns, showing the teams on each alliance and giving the user the opportunity to cherrypick data from only some of the teams.
    blue_alliance_col, red_alliance_col = st.columns(2)
    with blue_alliance_col:
        st.write("**Blue Alliance**")
        selected_teams = st.pills(
            label="",                       # The label for the selection (doesn't matter because we hide it)
            label_visibility="collapsed",   # Ignores the label altogether
            options=blue_teams,             # The selections is the blue_teams list
            default=blue_teams,             # The default selection should have all of the blue teams selected
            selection_mode="multi"          # Allow multiple selections
        )
        blue_teams = selected_teams
    with red_alliance_col:
        st.write("**Red Alliance**")
        selected_teams = st.pills(
            label="",                       # The label for the selection (doesn't matter because we hide it)
            label_visibility="collapsed",   # Ignores the label altogether
            options=red_teams,              # The selections is the red_teams list
            default=red_teams,              # The default selection should have all of the red teams selected
            selection_mode="multi"          # Allow multiple selections
        )
        red_teams = selected_teams

    # Just writes a horizontal line
    st.divider()

    # Creates the alliances list - a list of team lists
    alliances = [blue_teams, red_teams]
    # Generates the alliance names with the "Blue/Red Alliance" as well as the team numbers
    alliance_names = [
        f"Blue Alliance ({'/'.join([str(x) for x in blue_teams])})",
        f"Red Alliance ({'/'.join([str(x) for x in red_teams])})",
    ]

    # Writes the actual alliances view for the alliances in this match.
    utils.write_alliances_view(match_df, prescouting_df, alliances, alliance_names)

def main ():
    # Streamlit page title and short explanation
    st.title("Match Scouter")
    st.write("For formulating match strategies/viewing data for future matches.")

    schedule: list = utils.get_event_schedule(st.session_state["currentEventCode"])
    # If match data not found, we can't proceed.
    if len(schedule) == 0:
        st.write("No match data found in the MongoDB.")
        return

    # Gets the match and prescouting data DataFrame
    match_df: DataFrame = utils.get_match_data()
    prescouting_df: DataFrame = utils.get_prescouting_data()

    # Writes input fields that return a match key selected by the user
    match_key: str = match_selector("match_scouter")

    st.divider()

    # Writes the match summary
    write_match_summary(match_df, prescouting_df, match_key)

main()
